### ISSUE TITLE
4D conversion issue

### ISSUE THREAD

**Issue by benjaminirving** [neurolabusc/dcm2niix#11]
Hi, 

Firstly, thanks, dcm2niix looks like it's going to be very useful. 

I've come across an issue when converting 4D DCE-MRI scans. 

When converted, the nifti's zaxis dimensions have been halved and the temporal slices have been doubled. So slices from the axial volume have been added to the temporal dimension instead. 

E.g. a volume of dimensions 512x512x56x25 becomes 512x512x28x50 when converted using dcm2niix. Converted using the older dcm2nii tool works fine for this volume. 

The dimensions are correctly captured in the header:

![selection_007](https://cloud.githubusercontent.com/assets/1849579/13112476/bc070728-d582-11e5-9aef-7131822d56d7.jpg)

![selection_006](https://cloud.githubusercontent.com/assets/1849579/13112482/c08fe12a-d582-11e5-896a-c9558019589c.jpg)

Alternatively, if you point me in the right direction, I can try and fix the bug myself. 

I've also included a few screenshots as examples. There also appears to be some flipping of the dimensions. 

Time point 14 (left converted using dcm2nii and right converted using dcm2niix)

![selection_008](https://cloud.githubusercontent.com/assets/1849579/13112695/d5141dc2-d583-11e5-91cc-289a5681394d.jpg)

Time point 15 (left converted using dcm2nii and right converted using dcm2niix)

![selection_009](https://cloud.githubusercontent.com/assets/1849579/13112698/d863fbaa-d583-11e5-8013-6a5ad1e6e7f9.jpg)

**Comment by neurolabusc** [comment]
Without a sample image this will be hard for me to trouble shoot. An orthogonal slice would also help (e.g. is this really a 56 slice volume or are there two echo, where the volume should be  512x512x56x25x2). The challenge here is that different vendors use different approaches to encoding this information. In any case I have added a stub for handling DICOM tag,element 0x0020, 0x0105 to  nii_dicom.cpp that should give you a good starting point
  https://github.com/neurolabusc/dcm2niix/blob/master/console/nii_dicom.cpp

**Comment by benjaminirving** [comment]
Thanks for the comments. I will follow up and see if I can provide data or debug it myself. 

This is a single volume with 56 axial slices. dcm2niix cuts off the top half of the volume and adds this images to every second temporal position. 

The sagittal view using the (old) dcm2nii conversion

![selection_011](https://cloud.githubusercontent.com/assets/1849579/13144940/742e6b12-d645-11e5-8e13-432ccbc92520.jpg)

The sagittal view using the dcm2niix conversion

![selection_010](https://cloud.githubusercontent.com/assets/1849579/13144951/80db6932-d645-11e5-99be-6871704bda67.jpg)

Let me investigate further and follow up later.

**Comment by benjaminirving** [comment]
The system is a GE Signa HDx

**Comment by benjaminirving** [comment]
OK it seems that for our data kLocationsInAcquisitionGE is getting a value from (0021, 104f) that is half the value of the actual number of axial slices. I assume this is an error in the dicom header.

**Comment by neurolabusc** [comment]
Nice work! That would explain it. Since 0021,104f is a private tag I think a good solution would be to give the public 0020,0105 precedence.

I have a guess as to what is happening. I think this sequence has GE’s interpolation function switched on, so it is generating twice as many slices as there are locations. Therefore the DICOM is reported the number of slices acquired, but not the number stored.

If my hunch is correct, I would like to think we have evidence of it in one of the tag, perhaps check

0043, 1079 'US' LocationsInAcquisition
2001, 1018 'SL' LocationsInAcquisition
2001, 102D 'SS' StackNumberOfSlices

-c

Chris Rorden, PhD
Endowed Chair of Neuroimaging
Department of Psychology
University of South Carolina
Columbia, SC 29208, USA
phone +1 803 404 2573
email rorden@sc.edu<mailto:rorden@sc.edu>
web www.mricro.com<http://www.mricro.com>


On Feb 18, 2016, at 11:15 AM, Benjamin Irving <notifications@github.com<mailto:notifications@github.com>> wrote:


OK it seems that for our data kLocationsInAcquisitionGE is getting a value from (0021, 104f) that is half the value of the actual number of axial slices. I assume this is an error in the dicom header.

**Comment by neurolabusc** [comment]
Thanks for testing my fix and for your detective work. I have now committed this to the main branch and I am closing this issue. To summarize, the GE tag 0021,104f is not always reliable (presumably due to interpolation), so giving priority to 0020,0105 is a suitable work-around.

**Comment by benjaminirving** [comment]
Great. Happy to help.
