### ISSUE TITLE
Fork to allow yaml batch processing

### ISSUE THREAD

**Issue by benjaminirving** [neurolabusc/dcm2niix#13]
Hi, 

I've created a fork of dcm2niix to allow batch processing of dicoms using a yaml config file. 

https://github.com/benjaminirving/dcm2niix-batch

I'm assuming you don't want this in the core code otherwise I would be happy to create a pull request. The code is a quick modification but gets the job done.  

Best wishes, 
Ben

**Comment by neurolabusc** [comment]
This looks really useful. I have added you as a collaborator. Can I suggest you fold this into the main version? While the BSD allows you to create a branch, I think this would be a real asset. Thanks!

**Comment by benjaminirving** [comment]
Sure. That's sounds great. 

When I get a chance, I'll create a new branch on this project and can merge once we're happy. 

A few things:
- It does require an extra library dependency: yaml-cpp
- I'm currently requiring c++11
- Would you prefer it all to be run from dcm2niix or should there be a second binary for batch processing e.g. dcm2niix-batch?
- Any other suggestions or preferences?

**Comment by neurolabusc** [comment]
This seems fine. I would suggest we do this with a compiler switch, that allows the user to determine whether they want to enable this feature. Note I already do this to allow the user to select the gz compression (miniz vs zlib) and JPEG2000 (none, OpenJPEG, Jasper):
  https://github.com/neurolabusc/dcm2niix
I do think we want to make sure our code supports both GCC and Clang/LLVM, and I also recognize that many scientists like to run older operating systems (CentOS 6.6 seems popular with FSL crowd [gcc 4.4.7], and it seems some scientists still use OSX 10.6). 

"From there you can see that C++11 is supported since gcc 4.7 and gcc 4.4 has C++0x support."
  http://stackoverflow.com/questions/23523634/compiling-c11-on-g-4-4-7-in-red-hat-linux

So my sense is by using a compiler directive we could support these users.

**Comment by benjaminirving** [comment]
I've added a branch called batch_processing to the project and updated the README in that branch to explain the new options. 

Basically, it looked like it was going to be very messy to merge into a single binary so I've created the options to build a second `dcm2niibatch` binary that does batch conversion from the configuration file. 

This requires extra packages and c++11 but is built optionally from cmake by running `cmake -DBATCH_VERSION=ON ..`

See the updated read me file in the branch. 

Let me know if you're happy with this setup. I might also look into included your qt gui as a build option in the cmake file.
