### ISSUE TITLE
unable to find dicom images

### ISSUE THREAD

**Issue by mgxd** [neurolabusc/dcm2niix#15]
Hi,
When trying to run dcm2niix's conversion on dicom data, I am running into the following error:

`Compression will be faster with /usr/local/bin/pigz
Chris Rorden's dcm2niiX version 29Feb2016 (64-bit)
Version 29Feb2016 (64-bit)
Error: unable to find any DICOM images in /mindhive/xnat/dicom_storage/autoxy/mathias/ASD_01/dicom
Conversion required 2.130000 seconds.`

The command I'm using is
`dcm2niix -o path/to/output path/to/dicoms`

The data is compatible with dcm2nii. I've put a small subset of dicoms from a resting state in a [dropbox folder](https://www.dropbox.com/sh/uj9yj47ltjagy1k/AAC-5tLlFKrtaQaZTvGEB8L4a?dl=0), if that could help.

Thanks!
Mathias

**Comment by neurolabusc** [comment]
Hello,
  I am afraid the problem is with your files, not my software. Specifically, your files are not DICOM Part 10 compliant. Rather, this is a DICOM dataset without the DICOM file meta information. For more details please see

http://dicom.nema.org/dicom/2013/output/chtml/part10/chapter_7.html
http://fileformats.archiveteam.org/wiki/DICOM
http://nipy.org/nibabel/dicom/dicom_intro.html

I have released a new version of dcm2niix (22Mar2016) that converts these images, but this necessarily makes assumptions regarding byte-order and the implicit use of VR's: these settings are typically provided in the meta information wrapper. I would urge you to try to archive these in a DICOM part 10 compliant manner, as without this your dataset might pose problems with many popular tools and archival analyses.
