### ISSUE TITLE
dcm2niix fails to read files after compiling to JavaScript

### ISSUE THREAD

**Issue by chrisfilo** [neurolabusc/dcm2niix#27]
Steps to replicate:

1. [Install emscripten](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html)
1. Compile dcm2niix to JavaScript: `emcc -DmyDisableOpenJPEG -I. main_console.cpp nii_dicom.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp jpg_0XC3.cpp ujpeg.cpp -o dcm2niix.js`
1. Run dcm2niix: `node dcm2niix.js ~/Downloads/2475376/anat/`

Expected results:
```
Compression will be faster with /usr/local/bin/pigz
Chris Rorden's dcm2niiX version 20May2016 (64-bit)
Version 20May2016 (64-bit)
Found 192 DICOM image(s)
Convert 192 DICOM as /Users/filo/Downloads/2475376/anat/_MPRAGE_20200505000011_9 (256x256x192x1)
Conversion required 0.194481 seconds.
```

Instead got:
```
Compression will be faster with /usr/local/bin/pigz
Chris Rorden's dcm2niiX version 20May2016 (32-bit)
Version 20May2016 (32-bit)
Warning: output folder invalid /Users/filo/Downloads/2475376/anat/ will try /Users/filo/Downloads/2475376/anat/
Error: unable to find any DICOM images in /Users/filo/Downloads/2475376/anat/
Conversion required 0.006000 seconds.
```

It seems that the folder with dicom files needs to be explicitly mounted for this to work in emscripten (see https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html#filesystem-api-nodefs and the included example).

Being able to provide JS version of dcm2niix would open a whole new world of possibilities!

Here's the dcm2niix.js 
[dcm2niix.zip](https://github.com/neurolabusc/dcm2niix/files/300817/dcm2niix.zip)

**Comment by neurolabusc** [comment]
This would be a nice enhancement, in particular if we could modify a single C source code in such a way to support both C compiles as  well as emscripten conversion to javascript. I am unfamiliar with emscripten as well as JavaScript, but these links suggest that emscripten does not support direct loading and saving of files:
  https://github.com/kripken/emscripten/issues/1120
  http://stackoverflow.com/questions/23997312/how-do-i-read-a-user-specified-file-in-an-emscripten-compiled-library
  https://github.com/dreamlayers/em-dosbox/issues/4

**Comment by neurolabusc** [comment]
In general, I do not think the DICOM format is compatible with modern sandboxing techniques used by the operating systems as well as the web browsers. Typically, a single 3D DICOM image is saved as a series of 2D images, and viewing software needs to have permission to search a folder for files and then open multiple files. With sandboxing this is not possible, because the application does not have permission to do these operations. 

A good example of this is my Xcode application MRIcro
  https://github.com/neurolabusc/MRIcro
which can be compiled in two versions: one that meets the sandboxing requirements of the App Store (and is available from the App Store) and one that I distribute through NITRC. The sandboxed version does not include dcm2niix. To illustrate the behavior, try dropping a typical NRRD header (where a header is stored in a separate file from the raw image data) onto my App store application. A new dialog box pops up asking you to manually select the corresponding image. This dialog is required since the application does not have permission to open the 2nd file (it is outside the sandbox).

This is not a limitation of my software, rather the design of DICOM datasets is fundamentally incompatible with the intentions of Sand Boxing. In one sense, this is a nice reason to use dcm2niix: it converts images from a format that is not suitable for sandboxing (DICOM) to one that is (NIfTI). Though you still have issues with NIfTI if you want to read additional files (e.g. BIDS, BVEC, BVAL are typically saved as additional files).

**Comment by chrisfilo** [comment]
Thanks for looking into this!
I have not had a chance to test this yet, but I think you are right about having to pre mount the directory with dicoms before calling JS version of dcm2niix (your first entry), but I do not necessarily agree with the second comment. At least in the context of Node.js (which is still very useful) one can search a folder for files: https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options.

**Comment by neurolabusc** [comment]
I think you want to decide what problem you are trying to solve. What niche do you want to fill to justify the conversion effort.

In other words, what benefit does a JavaScript application provide that the natively compiled C code does not? It seems like the benefit of having these features in JavaScript would be to embed them in a browser, but once you do this you have to live inside the sand box.

I certainly think JavaScript, Python etc lend themselves to code that is more readable, clear, and easier to maintain than C code. However, I doubt an automated converter from C to JavaScript will yield pretty JavaScript code. At that stage do you fork the JavaScript and tune the code base? In that case you now have two independent projects. I am not a personal fan of the C language, but the major compilers for this language (gcc, clang/llvm, visual studio) all generate really optimized code. Given the size of modern multi band datasets and methods like real-time fMRI, I think that performance is a nice (and perhaps defining) feature of my software. 

In terms of a readable, scriptable DICOM-to-NIfTI converter, I am a huge fan of Xiangrui Li's dicm2nii Matlab code. He and I have worked together so our tools typically do the same thing. I think the niche for dcm2niix is in high performance (as well as better support for clinical modalities like CT). On the other hand, dicm2nii is ideal for scripting and personal modification. While it is Matlab-based, I am pretty sure it is compatible with Octave and given the popularity of SPM in our field (which is Matlab based) I do not think this is a huge constraint. 

Finally, I think the nipype approach fills a good niche. It provides a nice Python scripting wrapper that can call dcm2niix (or other converters). This provides the performance of the natively compiled converter in a nice scripting language wrapper.
