### ISSUE TITLE
Output filename sometimes get appended a prefix depending on the naming of the folder containing the .dcm files

### ISSUE THREAD

**Issue by jvarada** [neurolabusc/dcm2niix#42]
If I have my DICOM files in a folder named 'mr_0013-e02', and run the following command from inside that folder, `dcm2niix -z y -b y -f test .`, the output filenames come out as `_e2_phtest.json` and `_e2_phtest.nii.gz` rather than just `test.json` and `test.nii.gz`.

This does not happen if the folder does not have the "-e02" part. 

Is this a parsing bug somewhere or is there a way to get around this?

**Comment by neurolabusc** [comment]
I can not replicate your problems, see below for my attempts to emulate your issue using the latest build in OSX 10.11. Can you tell me the OS you are using, which version of my software you are using. If the latest build still creates problems, could you send me an email with a dropbox to some sample images. 

Chriss-MacBook-Pro:mr_0013-e02 rorden$ /Users/rorden/Documents/cocoa/dcm2niix/console/dcm2niix -z y -b y -f test .
Chris Rorden's dcm2niiX version 15Aug2016 (64-bit)
Found 2 DICOM image(s)
Convert 2 DICOM as ./test (64x64x36x2)
compress: "/usr/local/bin/pigz" -n -f "./test.nii"
Conversion required 0.003005 seconds.
Chriss-MacBook-Pro:mr_0013-e02 rorden$ ls -l
total 2168
-rw-r--r--  1 rorden  staff  384454 Mar 10  2014 dcm1
-rw-r--r--  1 rorden  staff  384458 Mar 10  2014 dcm2
-rw-r--r--  1 rorden  staff     576 Aug 26 13:01 test.json
-rw-r--r--  1 rorden  staff  333733 Aug 26 13:01 test.nii.gz

**Comment by jvarada** [comment]
I am unable to provide the specific sample datasets at the moment since we are still working on anonimizing them. 

However, I have found that the addition of `_e2_ph` is not dependent on the folder name as I believed, rather it seems to be dependent on the dicom header properties of the files (since I would get the behavior for my EPI fieldmap files, but not for T1 files. Inspecting dcm2niix's source code, I believe the responsible lines for this behavior are [L752](https://github.com/neurolabusc/dcm2niix/blob/a5c778255b6e3a44a5eea63583e825737832b52e/console/nii_dicom_batch.cpp#L752) and [L756](https://github.com/neurolabusc/dcm2niix/blob/a5c778255b6e3a44a5eea63583e825737832b52e/console/nii_dicom_batch.cpp#L756.)

Is there a way to turn these options off?

**Comment by neurolabusc** [comment]
This is a feature, not a flaw of my software. You have converted a MRI field map, where two echo times were used. Typically a field map generates the standard magnitude images as well as a phase image (which you can use with FSL's Fugue to undistorted your image). The image from the second echo has the name 'e2' appended to remind you that this is the longer echo time. The phase map has the label 'ph' to remind you it is a phase map. This avoids naming conflicts with the standard magnitude images and the first echo. That way, you can place all the images from the sequence in the folder and the magnitude, phase, and echo images are all saved with logical file names. If you open the 'ph' image with a NIfTI viewer software like MRIcroGL, you will see that it looks different from standard magnitude images.

**Comment by dangom** [comment]
Would it be possible to deativate this feature with a flag? The user taking full responsibility for what happens?

I ask because I usually sort my dicoms (for archiving purposes) in separate folders - each folder containing a different echo (or mag./phase) series - before conversion. Converting from sorted folders makes it easy to dcm2niibatch convert files directly into a BIDS structure, but I always have to take the extra step of batch renaming all files to remove _e# and _ph suffixes.

**Comment by WillForan** [comment]
To resolve this , I add 2 lines after calling `dcm2niix`. 
1) run dcm2niix
1) Find a recent (within 2 min) file named similar (may or may not have prefix) to what we expect.
2)  rename if it's not exactly what we want
```bash
dcm2niix_nosuffix() {
  name="$1"; shift; inputdir="$1"; 
  dcm2niix -f '$name%%' -z y -b y -o ./ "$inputdir"
  newname="$(find . -maxdepth 1 -type f -name "$name*.nii.gz" -ctime -2)"
  [ -z "$newname" -a  -r "$newname"  -a "$newname" != "./$name.nii.gz" ] && mv "$newname" "$name.nii.gz"
}
```

**Comment by neurolabusc** [comment]
@dangom : perhaps you can describe your desired behavior. The issue here is that we typically have 3 NIfTI images that have the same protocol name, series number etc. So if a user converts images with "-f %p_%s" the output name should have the protocol name followed by the series, e.g. "fieldmap_4". Without my feature both the 1st and 2nd echo would have this name, and it would be ambiguous which is saved. My software will create "fieldmap_4" for the first echo and "fieldmap_e2" for the second. In theory, the phase map should always be saved as a separate series (it is a derived images, and the DICOM standard requires derived images are saved with a different series than the raw images), but as I recall previous versions of Siemens software saved these as the same series as the raw magnitude images. Therefore, my solution is to ensure unique names that are do not overwrite each other. Are you happy with @WillForan 's solution, or do you want to suggest what behavior would be ideal?

**Comment by dangom** [comment]
I don't think the default behaviour should be changed.

To put things into context, at least from my experience working with Siemens scanners, there is no consistency across the reconstruction routines used for different sequences. 
Some multiecho-capable sequences (some fmapping sequences, and notably CMRR's EPI) will save all echoes to the same Series. Other sequences (Siemens MBME WIP) will save them to separate Series.
Because I work a lot with said WIP, I never have the problem of ambiguous files, since my series names are unique for each echo (and phase, if applicable). That is why I don't need dcm2niix to append suffixes. 

Changing the default behaviour could lead to surprises for other users, though, so I'm fine using Will's workaround.
