### ISSUE TITLE
Is the _ADC image supposed to contain all directions?

### ISSUE THREAD

**Issue by blakedewey** [neurolabusc/dcm2niix#44]
When I convert a DTI dataset, I end up with two NIfTI files, one with "_ADC" and one without. The one without removes the added mean diffusion image at the end of the original dataset, but the one with "_ADC" contains all original directions and the final mean image. Is this the intended result? My original though was that this extra file should just have the removed volume.

**Comment by neurolabusc** [comment]
See https://www.nitrc.org/forum/forum.php?thread_id=7028&forum_id=4703

I assume your data came from a Philips scanner where the console was set up to derive an ADC image. In this case, the Philips system stored not only the raw data, but also used the raw data to derive an ADC image. Note that tools like FSL are designed to handle only raw data (they derive their own derived images like MD, FA, V1, L1 etc from the raw data), and including a derived image in the 4D image will disrupt these tools. Therefore, my software not only saves the data as recorded by your scanner (img_ADC.nii) but also the raw-only dataset where the derived image has been removed (img.nii, img.bvec, omg.bval). The latter is what you would use for analysis with other tools. 

In general, I would recommend you not calculate an ADC map on your scanner. You will get much better derived images after you run TOPUP/EDDY. So these images are redundant.

The dcm2niix kludge allows Philips users to rapidly analyze their DTI datasets. If your data was stored as a DICOM dataset (rather than as Philips proprietary PAR/REC format) I strongly suggest you contact them and tell them to store derived data as a separate series from the raw data. In fact, not doing so is a clear violation of the DICOM standard and those datasets are not strictly DICOM compliant.

**Comment by neurolabusc** [comment]
I now describe how Philips includes [derived images along with the raw diffusion images](https://github.com/rordenlab/dcm2niix/tree/master/Philips). While dcm2niix calls the file with the derived images "ADC", in practice they are often isotropic images. In any case, you do not want these for analyses, and upcoming versions of dcm2niix will not store these if you choose the "i"ignore parameter.
